### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by alex-mathew** [alex-mathew/MapMint4ME#1]
- [x] Fork the MapMint4ME Github repository and create a task list in the issues section of the repository
 - [ ] Setup Android Studio for development
 - [ ] Build the MapMint4ME application on Android Studio
 - [ ] Implement a basic AR feature in the MapMint4ME Android application
